food/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'food'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<meal_id>[0-9]+)/addFood$', views.addFood, name='addFood'),
    url(r'^animal/add/$', views.AnimalCreate.as_view(), name='animal-add'),
    url(r'^animal/(?P<pk>[0-9]+)/$', views.AnimalUpdate.as_view(), name='animal-detail'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # url(r'^polls/', include('polls.urls')),
    url(r'^food/', include('food.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

food/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

class Nutrient(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, null=True, blank=True)
    group = models.ForeignKey('NutrientGroup', null=True, blank=True)
    def __str__(self):
        return self.name

class NutrientGroup(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    def __str__(self):
        return self.name


class Animal(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('food:animal-detail', kwargs={'pk':self.pk})


class AnimalNutrient(models.Model):
    animal = models.ForeignKey('Animal')
    nutrient = models.ForeignKey('Nutrient')
    quantity = models.FloatField()
    quantityUnit = models.CharField(max_length=5)
    def __str__(self):
        return "{}'s daily {} need".format(self.animal, self.nutrient)


class Food(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, null=True, blank=True)
    majorNGroup = models.ForeignKey('NutrientGroup', null=True, blank=True)
    servingSize = models.IntegerField(null=True, blank=True)
    calories = models.IntegerField(null=True, blank=True)
    kilojouls = models.IntegerField(null=True, blank=True)
    servingUnit = models.CharField(max_length=200, null=True, blank=True)
    nutrition = models.ManyToManyField(Nutrient, through='FoodNutrient')
    cost = models.FloatField(null=True, blank=True)
    def __str__(self):
        return self.name

# relationship between food and nutrition
class FoodNutrient(models.Model):
    food = models.ForeignKey('Food', null=True, blank=True)
    nutrient = models.ForeignKey('Nutrient', null=True, blank=True)
    quantity = models.FloatField(default=1.0)
    quantityUnit = models.CharField(max_length=5, default='g')
    def __str__(self):
        return "{}'s {}".format(self.food, self.nutrient)


class Meal(models.Model):
    name = models.CharField(max_length=20)
    food = models.ManyToManyField(Food, through='MealFood')
    def __str__(self):
        return self.name


class MealFood(models.Model):
    food = models.ForeignKey('Food')
    meal = models.ForeignKey('Meal')
    quantity = models.FloatField(default=1.0)
    quantityUnit = models.CharField(max_length=5, default='g')
    def __str__(self):
        return "{} {}".format(self.food, self.meal)

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
# import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Nutrient(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, null=True, blank=True)
    group = models.ForeignKey('NutrientGroup', null=True, blank=True)

class NutrientGroup(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)

food/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Meal, Nutrient, Food, MealFood, Animal
import logging

logger = logging.getLogger(__name__)

class IndexView(generic.ListView):
    template_name = 'food/index.html'
    context_object_name = 'meals_list'

    def get_queryset(self):
        return Meal.objects.all()

    def get_context_data(self):
        d = {'a' : 'a'}
        return d

class DetailView(generic.DetailView):
    model = Nutrient
    template_name = 'food/detail.html'


class AnimalCreate(CreateView):
    model = Animal
    fields = ['name', 'description']

class AnimalUpdate(UpdateView):
    model = Animal
    fields = ['name', 'description']



def addFood(request, meal_id):
    meal = get_object_or_404(Meal, pk=meal_id)
    food_list = Food.objects.all()
    try:
        selected_food = Food.objects.get(pk=request.POST['food'])
        logger.info(request.POST['food'])

    except (KeyError, Food.DoesNotExist):
        pass
    else:
        mf = MealFood()
        mf.food = selected_food
        mf.meal = meal
        mf.save()

    return render(request, 'food/addFood.html', {'meal' : meal, 'food_list' : food_list})

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didnt select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

food/templates/food/addFood.html
<style>
    * {
        font-family: arial;
        font-size: 14px;
    }
    h2 {
        font-size: 16px;
    }
    body {
        background-color: #ccccff
    }
    ul li, p, a {
        line-height: 18px;
    }
    td, th {
        border: 1px solid green;
        width: 35%;
    }
    table {
        border: 1px solid green;
        margin: 10px 20px;
        width: 50%;
    }
</style>

<h2> {{ meal.name }} </h2>

{{ food_id }}

<form action="{% url 'food:addFood' meal.id %}" method="post">
    {% csrf_token %}

    <table>
        <tr> <th>Food</th>
            <td>
                <select name="food">
                {% for food in food_list %}
                    <option value="{{ food.id }}"> {{ food.name }} </option>
                {% endfor %}
                </select>
            </td>
        </tr>
        <tr><th>Quantity</th>
            <td>
            <input type="text" name="quantity"/>
            </td>
        </tr>
        <tr><th>Unit</th>
            <td>
            <input type="text" name="quantityUnit"/>
            </td>
        </tr>
        <tr><th>&nbsp;</th>
            <td>
            <input type="submit" value="add"/>
            </td>
        </tr>
    </table>

</form>

<a href="{% url 'food:index' %}"> <-Back </a>

food/templates/food/animal_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'food/form-template.html' %}
    <div>
        <button type="submit">Submit</button>
    </div>
</form>

food/templates/food/detail.html
<style>
    h2 {
        font-family: arial;
        font-size: 16px;
    }
    body {
        background-color: yellow
    }
    ul li, p, a {
        font-family: arial;
        font-size: 14px;
        line-height: 18px;
    }
</style>

<h2> {{ nutrient.name }} </h2>

<p> Group: {{ nutrient.description }} </p>

<p> {{ nutrient.description }} </p>

<a href="../"> <-back </a>

food/templates/food/form-template.html
{% for field in form %}
    <div class="form-group">
        <span> {{ field.error }} </span>
    </div>

    <label> {{ field.label_tag }} </label>
    <div> {{ field }} </div>

{% endfor %}

food/templates/food/index.html
<style>
    * {
        font-family: arial;
        font-size: 14px;
    }
    h2 {
        font-size: 16px;
    }
    body {
        background-color: #ccccff
    }
    ul li, p, a {
        line-height: 18px;
    }
    td {
        border: 1px solid green;
        width: 35%;
        vertical-align: top;
        padding: 8px;
    }
    table {
        border: 1px solid green;
    }

</style>

<h2> Meal planner </h2>

<a href="https://www.bodybuilding.com/fun/fats_calculator.htm"/> calculator </a>

{{ context }}

<table>
    <tr><th colspan="2">Today</th>
    </tr>
    {% for meal in meals_list %}
        <tr>
            <td>
                {{ meal.name }}
                <ul> <!-- many to many relationship set -->
                {% for f in meal.mealfood_set.all %}
                    <li>{{ f.food.name }} - {{ f.quantity }}{{ f.quantityUnit }}</li>
                {% endfor %}
                </ul>
                <a href="{% url 'food:addFood' meal.id %}"> add food </a>
            </td>
            <td>
                <ul>
                    {% for f in meal.food.all %}
                        {% for n in f.foodnutrient_set.all %}
                            <li> {{ n.nutrient }} {{ n.quantity }} {{ n.quantityUnit }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </td>
        </tr>
    {% endfor %}
</table>

<p><a href="{% url 'food:animal-add' %}">Add animal</a></p>

food/templates/food/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}